---
- name: Day 3 Warm up
  hosts: looneytunes
  connection: ssh   # use the connection plugin, ssh.py (this is the default)
  gather_facts: no   # no need to define ansible_facts in this playbook

  vars:
    # the variable "st" is mapped to "directory"
    st: directory

  tasks:
  - name: "Create directory challenge"
    become_user: root
    become: true
    file:
        # the var "fileuser" is a host variable and defined in ~/mycode/inv/dev/hosts
        path: "/home/{{ item }}/challenge/"
        state: directory
        mode: "0755"
    loop: [bender, fry, zoidberg]
        
  - name: "Download file from Github"
    become: true
    get_url:
      url: https://raw.githubusercontent.com/csfeeser/ansible_essentials/main/data/downloadme.txt
      dest: "/home/{{ item }}/challenge/downloadme.txt"
    loop: [bender, fry, zoidberg]

  - name: "Replacing PLACEHOLDER"
    replace:
      path: "/home/{{ item }}/challenge/downloadme.txt"
      regexp: "PLACEHOLDER"
      replace: "JAMES"
      backup: yes
    loop: [bender, fry, zoidberg]
